### PR TITLE
Add dotnet template support

### PR DESCRIPTION
**Pull request by dahlsailrunner**
## PR Notes
The vast majority of the changes were to rename most instances of `CleanArchitecture` to `Clean.Architecture` (with a dot separating the words).  This was because (at least at the time of original creation) to support output names that included a dot, which is not uncommon) the source needed to have one.  I can't now find the posts that indicated that.  So by including a dot in the `sourceName` defined in the `template.json` file, the user can provide a `-o` value when they create their new project either with OR without dots in the output name and it will work fine.  This was not the case if a `sourceName` of `CleanArchitecture` was used.

The actual template support was pretty easy - just the `.template.config/template.json` file, and the `CleanArchitecture.nuspec` file.  These changes were on the second commit -- along with a functional test that I overlooked in the rename process.

Both the original solution (renamed `Clean.Architecture.sln`) and any projects created from the template are runnable and all tests pass.

## README content
Here is some information that should probably go into the readme file (I wasn't sure how to update it since I didn't know if you already have a channel to publish this template to NuGet.org or not, or whether it was something you'd want to do):

Simplest possible usage instructions (without publishing NuGet package to NuGet.org):

* Clone the repo into an empty folder
* Make sure you have the [nuget CLI](https://www.nuget.org/downloads) installed
* In the root directory, run `nuget pack`. This will create CleanArchitecture.Template.1.0.0.nupkg.
* Make sure you have the [dotnet CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/) installed
Run `dotnet new -i CleanArchitecture.Template.1.0.0.nupkg`. This will install the templates from this package into the dotnet CLI.

Now to create a brand new project using the template:

Navigate to the directory where you will put the new solution.
Run `dotnet new clean-arch -o Your.ProjectName` where `Your.ProjectName` is whatever you want to name the project.
The `Your.ProjectName` directory and solution file will be created, and inside that will be all of your new solution
contents, properly namespaced and ready to run/test.

**NOTE:**
This could be published to NuGet.org if you/we/I have an account established there (I don't at this time).

If we did get this published to NuGet.org, then the top list of "simplest steps" would be simply this:

`dotnet new -i CleanArchitecture.Templates`

This command would install the template(s) from this NuGet package from the default NuGet sources and
use the latest version.

### CODE REVIEW

**Comment by dahlsailrunner** [comment]
This can replace PR #86 .  The animated gif from that PR is totally still valid though and could be included on the readme if desired.

**Comment by dahlsailrunner** [comment]
Pretty sure this was where I found the need to include the `.` (dot) in the `sourceName`.  https://github.com/dotnet/templating/issues/402

**Comment by ardalis** [comment]
I'm starting to think my build check is never going to complete. Thanks for this @dahlsailrunner and sorry for the long delay. Haven't been keeping up with this project until now.

**Review by ardalis — APPROVED** [review]

**Comment by ardalis** [comment]
Ok I just ran this locally and the nupkg is 233MB. How do I avoid that?
image

**Comment by ardalis** [comment]
Seems to be all the bin folders. I'll try deleting them all before doing the pack.
image

**Comment by ardalis** [comment]
Hmm. netcoreapp5.0 includes a bunch of runtimes in bin. Nuget pack builds before it packs (of course) so doing a dotnet clean first doesn't really help. Need a flag to tell net5 not to include all that crap.
image

**Comment by ardalis** [comment]
Modified nuspect file and got it down to 1MB.
```
  <files>
    <file src=".\**" target="content" exclude="**\bin\**;**\obj\**;**\.git\**;**\.github\**;**\*.user;**\.vs\**;**\.vscode\**" />
  </files>
```

**Comment by dahlsailrunner** [comment]
Really good to know about the `nuspec` file update.  That will come in handy.  I haven't spent too much time in the .NET 5 world yet -- just getting started there.  And you beat me to the punch on the "get rid of bin and obj folders before you pack" notion.  I had found that earlier and would have told you about that if you were still getting large packages.  Thanks!

**Comment by ardalis** [comment]
It's all good, thanks for the idea and initial work getting it working. I'm teaching a workshop on clean architecture tomorrow and I'd like for folks to be able to use dotnet new to get started so I wanted to get it published to nuget.org. And now it is! I've updated the README accordingly.

**Comment by dahlsailrunner** [comment]
That's awesome!  and good luck tomorrow -- i'm sure it'll be awesome.  If there's anything else i might be able to do to help don't hesitate to let me know.  Cheers, and hope you are well.

**Pull request merged**
