### PR TITLE
Use injected logger directly in email sender classes

### PR DESCRIPTION
**Pull request by samanazadi1996**
This pull request changes the email sender classes to use the injected logger directly in their methods.

### CODE REVIEW

**Comment by KyleMcMaster** [comment]
@ardalis mentions wanting to use primary constructor parameters only to initialize fields in this blog post. I believe we would want to keep the code the way it was as the parameters are mutable while the private readonly fields are not.
https://blog.nimblepros.com/blogs/where-csharp-primary-constructors-make-sense/

**Review by ardalis — COMMENTED** [review]
My preference is to only se primary constructors for field initialization.

See 

https://blog.nimblepros.com/blogs/where-csharp-primary-constructors-make-sense/

**Comment by samanazadi1996** [comment]
@ardalis Branch conflict is resolved

**Comment by ardalis** [comment]
I don't think we need this in its current state so closing.

**Pull request closed without merging**
