### PR TITLE
Adds Aspire

### LINKED ISSUE #846: Add Aspire
Add Aspire to the template for .NET 9 version.

- Better yet, make it add aspire only if an option is selected at the command line (e.g. `-aspire`)

### PR DESCRIPTION
**Pull request by benjaminmishra**
Fixes #846 

Adds .NET Aspire specific parts to the template. Also introduces a boolen flag `--aspire` that allows template users to choose if they want Aspire included in the template during creation.

The following projects were added to the template:
- src/Clean.Architecture.AspireHost
- src/Clean.Architecture.ServiceDefaults
- tests/Clean.Architecture.AspireTests

The template.json file was modified
- Adds a new symbol called "aspire"
- Adds conditional inclusion/exclusion of above mentioned project folders based on the aspire flag
- Adds a PostAction that inlcudes the aspire sepcific projects to the solution if the aspire flag is set to true.

New PackegeReferences were added to Directory.Packages.Props to conditionally add references based on the aspire flag.

### CODE REVIEW

**Comment by ardalis** [comment]
What's left for this to be ready to merge?

**Comment by benjaminmishra** [comment]
Hi @ardalis , The test that I added in the AspireHost test project is failing. Was investigating it,  but I recently noticed that we have a comment about it in the [ListContributorsQueryService.cs](src/Clean.Architecture.Infrastructure/Data/Queries/ListContributorsQueryService.cs) file that its expected with In memory databases. Unfortunately by default aspire uses in memory database to do integration testing. So was wondering if we need to have a real test in the aspire test project at all ?

**Comment by ardalis** [comment]
probably not. Alternately use a fake version of that service but that's probably not a good integration test...

**Comment by benjaminmishra** [comment]
Alright , I will remove it and publish the PR or should I just leave it as a comment ?

**Comment by ardalis** [comment]
Go ahead and remove it.

**Comment by benjaminmishra** [comment]
@ardalis this is now ready to be merged

**Comment by ardalis** [comment]
Thanks!

**Pull request merged**
