### PR TITLE
Upgrade to .NET 8

### LINKED ISSUE #612: Update to target latest net8 for Nov 2023 release

### PR DESCRIPTION
**Pull request by KonH**
Closes #612

### CODE REVIEW

**Comment by KonH** [comment]
For now I update only .NET target, should I upgrade all corresponding dependencies also?

**Comment by ardalis** [comment]
Yes, please

**Comment by KonH** [comment]
Made it in a separate commit, because I'm not sure that it makes sense to upgrade to preview versions which are available now.

**Comment by KonH** [comment]
Any updates?

**Comment by ardalis** [comment]
I'll probably merge it soon and publish a -preview to nuget

**Pull request merged**
