### PR TITLE
Created support for dotnet CLI template

### PR DESCRIPTION
**Pull request by dahlsailrunner**
I've updated the newest version of the repo to support the template package.  It uses the `nuget pack` flavor of packaging versus the `dotnet pack` flavor.  

Here is some information that should probably go into the readme file (I wasn't sure how to update it since I didn't know if you already have a channel to publish this template to NuGet.org or not, or whether it was something you'd want to do):

Simplest possible usage instructions (without publishing NuGet package to NuGet.org):
* clone the repo into an empty folder
* Make sure you have the nuget CLI installed
* In the root directory, run `nuget pack`.  This will create `CleanArchitecture.Template.1.0.0.nupkg`.
* Make sure you have the dotnet CLI installed
* Run `dotnet new -i CleanArchitecture.Template.1.0.0.nupkg`.  This will install the templates from this package into the dotnet CLI.

Now to create a brand new project using the template:
* Navigate to the directory where you will put the new solution.
* Run `dotnet new clean-arch -o Your.ProjectName` where `Your.ProjectName` is whatever you want to name the project.

The `Your.ProjectName` directory and solution file will be created, and inside that will be all of your new solution 
contents, properly namespaced and ready to run/test.

NOTE: 
This could be published to NuGet.org if you/we/I have an account established there (I don't at this time).

If we did get this published to NuGet.org, then the top list of "simplest steps" would be simply this:

`dotnet new -i CleanArchitecture.Templates`

This command would install the template(s) from this NuGet package from the default NuGet sources and 
use the latest version.

### CODE REVIEW

**Comment by dahlsailrunner** [comment]
Here's a screen recording that may help.  We can include in the readme if you think it helps.

CleanArch

**Comment by ardalis** [comment]
Can you update this and I'll try to merge it.

**Comment by dahlsailrunner** [comment]
I'll try to update it before the end of the week.

**Comment by dahlsailrunner** [comment]
I'm thinking the best thing for me to do is simply re-clone your main branch and make the changes again.  Then create a new PR and abandon this one.  Sound ok?

**Comment by ardalis** [comment]
I agree that's probably best at this point, thanks!

**Comment by dahlsailrunner** [comment]
I think you can probably kill this PR since the other one was merged.

**Pull request closed without merging**
